site_name: Olivier’s Theme for Obsidian
site_description: User Guide for Olivier’s Theme 2.0 – palettes, reading/writing modes, cssclasses.
site_url: https://olivierps.github.io/Olivier-s-Theme/  # adapte à ton user/org et repo

repo_name: OlivierPS/Olivier-s-Theme
repo_url: https://github.com/OlivierPS/Olivier-s-Theme

theme:
  name: material

nav:
  - Home: index.md
  - General:
    - General settings: general.md
    - glossary.md
  - Colors:
    - Light mode colors: light-mode-colors.md
    - Dark mode colors: dark-mode-colors.md
    - Text colors: text-colors.md
  - Reading & writing:
    - Reading mode: reading-mode.md
    - Writing / Editing mode: writing-mode.md
    - Reading vs Writing – mental modes: reading-vs-writing.md
    - Displaying Bases: displaying-bases.md
  - cssclasses:
    - Visual catalogue of CSS classes: css-classes.md
    - Niceties & cssclasses: niceties-and-cssclasses.md
  - samples:
    - color-samples-light.md
    - color-samples-dark.md
    - text-colors.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - attr_list
  - tables
  - codehilite
